---
title: "Report"
author: "`r Sys.getenv('USER')`"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    flexdashboard::flex_dashboard:
        orientation: rows
params:
    indir: "../../../results_run64_sup_v5.0.0/samples"
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE)
```




```{r include=FALSE}
library(tidyverse)
library(gt)
library(flexdashboard)
library(patchwork)
library(reactable)
library(htmltools)
source("lib_typing.R")

fct_reorder2_hclust <- function(.f, .y, .value) {
	.f <- as_factor(.f)
	if (nlevels(.f)<2) return(.f)
  wide <- tibble(f = .f, y = .y, value = .value) %>%
    pivot_wider(names_from = f, names_expand = TRUE, id_expand = TRUE, values_from = value,values_fill = 0) %>%
    column_to_rownames("y") %>%
    as.matrix() %>%
    t()
  h <- hclust(dist(wide),method="ward.D2")
  fct_relevel(.f,h$labels[h$order])
}

reactable_bar_style <- function(width = 1, fill = "#e6e6e6", height = "75%", align = c("left", "right"), color = NULL) {
  align <- match.arg(align)
  if (align == "left") {
    position <- paste0(width * 100, "%")
    image <- sprintf("linear-gradient(90deg, %1$s %2$s, transparent %2$s)", fill, position)
  } else {
    position <- paste0(100 - width * 100, "%")
    image <- sprintf("linear-gradient(90deg, transparent %1$s, %2$s %1$s)", position, fill)
  }
  list(
    backgroundImage = image,
    backgroundSize = paste("100%", height),
    backgroundRepeat = "no-repeat",
    backgroundPosition = "center",
    color = color
  )
}

reactable_select_filter <- function(element_id) {
	function(values, name) {
      tags$select(
        onchange = sprintf("Reactable.setFilter('%s', '%s', event.target.value || undefined)", element_id, name),
        tags$option(value = "", "All"),
        lapply(unique(values), tags$option),
        "aria-label" = sprintf("Filter %s", name),
        style = "width: 100%; height: 28px;"
      )
  }
}

reactable_percent_colDef <- function() {
	colDef(
				style = 'font-family: "Fira Mono", Consolas, Monaco, monospace; white-space: pre;',
	      format = colFormat(digits = 1,suffix = "%"),
				minWidth=40
	)
}
```


```{r include=FALSE}
db <- db_load(params$indir)
assemblies <- summarise_assembly(db)
contigs <- summarise_contigs(db)
```


# Summary

Row
-------------------------

### Assemblies
```{r}
valueBox(nrow(assemblies),"Samples",color = "coral")
```

### Contigs
```{r}
valueBox(nrow(contigs),"Contigs",color = "info")
```

### Plasmids
```{r}
valueBox(sum(contigs$is_plasmid),"Plasmids",color = "info")
```

Row
-------------------------

### Samples Identity: Species/ST
```{r}
bind_rows(
		assemblies |> 
			group_by(
				id=str_c("lev1",genus_name,sep="-"),
				label=genus_name,
				parent=""
			) |> count(),
		assemblies |> 
			group_by(
				id = str_c("lev2",genus_name,species_name,sep="-"),
				label = species_name,
				parent = str_c("lev1",genus_name,sep="-")
			) |> count(),
		assemblies |> 
			group_by(
				id = str_c("lev3",genus_name,species_name,mlst_type,sep="-"),
				label = mlst_type,
				parent = str_c("lev2",genus_name,species_name,sep="-")
			) |> count()
) |>
plotly::plot_ly(
		ids = ~id,
		labels = ~label,
	  parents = ~parent,
	  values = ~n,
	  type = 'sunburst',
	  branchvalues = 'total'
) %>%
plotly::config(displayModeBar=FALSE)
```



### amrfinder+
```{r}
amrfinderplus <- db |>
	select(assembly_id,amrfinderplus) |>
	unnest(amrfinderplus)
bind_rows(
	 amrfinderplus |>
			group_by(
				id=str_c(Class),
				label=Class,
				parent=""
			) |> summarize(
				n = n(),
				hovertext = str_glue("{n} hits in {n_distinct(assembly_id)} samples\n")
			),
	 amrfinderplus |>
			group_by(
				id=str_c(Class,Subclass),
				label=Subclass,
				parent=Class
			) |> summarize(
				n = n(),
				hovertext = str_glue("{n} hits in {n_distinct(assembly_id)} samples\n")
			),
	 amrfinderplus |>
			group_by(
				id=str_c(Class,Subclass,resistance_name),
				label=resistance_name,
				parent=str_c(Class,Subclass),
			) |> summarize(
				n = n(),
				hovertext = str_glue("{n} hits in {n_distinct(assembly_id)} samples\n")
			)
) %>%
plotly::plot_ly(
		ids = ~id,
		labels = ~label,
	  parents = ~parent,
	  values = ~n,
		hovertext = ~hovertext,
	  type = 'sunburst',
	  branchvalues = 'total'
) %>%
plotly::config(displayModeBar=FALSE)
```





# Plasmids

Row
-------------------------
```{r}
amrfinderplus <- db |>
	select(assembly_id,amrfinderplus) |>
	unnest(amrfinderplus)
bind_rows(
	 amrfinderplus |>
			group_by(
				id=str_c(Class),
				label=Class,
				parent=""
			) |> summarize(
				n = n(),
				hovertext = str_glue("{n} hits in {n_distinct(assembly_id)} samples\n")
			),
	 amrfinderplus |>
			group_by(
				id=str_c(Class,Subclass),
				label=Subclass,
				parent=Class
			) |> summarize(
				n = n(),
				hovertext = str_glue("{n} hits in {n_distinct(assembly_id)} samples\n")
			),
	 amrfinderplus |>
			group_by(
				id=str_c(Class,Subclass,resistance_name),
				label=resistance_name,
				parent=str_c(Class,Subclass),
			) |> summarize(
				n = n(),
				hovertext = str_glue("{n} hits in {n_distinct(assembly_id)} samples\n")
			)
) %>%
plotly::plot_ly(
		ids = ~id,
		labels = ~label,
	  parents = ~parent,
	  values = ~n,
		hovertext = ~hovertext,
	  type = 'sunburst',
	  branchvalues = 'total'
) %>%
plotly::config(displayModeBar=FALSE)
```




# Tables

Row {.tabset}
-------------------------


### assemblies
```{r}
assemblies |>
	select(species_name,mlst_type,assembly_id,num_contig,assembly_length,GC,N50,orgfinder.species_name,orgfinder.ani) |>
	mutate(GC = 100*GC) |>
	reactable(
		pagination = FALSE,
		compact = TRUE,
	  defaultSorted = "mlst_type",
		defaultSortOrder = "desc",
	  defaultColDef = colDef(headerClass = "header", align = "left"),
		defaultExpanded = TRUE,
		groupBy = "species_name",
		filterable = TRUE,
		columns = list(
			mlst_type = colDef(
				minWidth=40
	    ),
			num_contig = colDef(
				minWidth=40
	    ),
			assembly_length = colDef(
	      style = function(value) {
	        reactable_bar_style(width = value / max(assemblies$assembly_length), fill = "#DDDDFF", color = "#000000")
	      },
	      format = colFormat(digits = 0,separators = TRUE,suffix = " bp"),
	      minWidth=60
	    ),
			GC = reactable_percent_colDef(),
			orgfinder.ani = reactable_percent_colDef(),
			N50 = colDef(
				style = 'font-family: "Fira Mono", Consolas, Monaco, monospace; white-space: pre;',
				format = colFormat(digits = 0,separators = TRUE,suffix = " bp"),
				minWidth=60
	    )
		),
		rowStyle = JS("function(rowInfo) {
	    if (rowInfo.level > 0) {
	      return { background: '#eee', borderLeft: '2px solid #ffa62d' }
	    } else {
	      return { borderLeft: '2px solid transparent' }
	    }
	  }"),
		elementId = "assembly-select",
		class = "feature-tbl assemblies-tbl"
	)
```


### contigs
```{r}
contigs |>
	left_join(assemblies,by="assembly_id",suffix = c("",".y")) |>
	select(species_name,assembly_id,contig_id,contig_length,GC,topology,is_plasmid) |>
	mutate(GC = 100*GC) |>
	reactable(
		pagination = FALSE,
		compact = TRUE,
	  defaultSorted = "contig_length",
		defaultSortOrder = "desc",
	  defaultColDef = colDef(headerClass = "header", align = "left"),
		defaultExpanded = FALSE,
		groupBy = c("species_name","assembly_id"),
		filterable = TRUE,
		columns = list(
			species_name = colDef(
				filterInput = reactable_select_filter('contigs-select')
			),
			contig_length = colDef(
	      style = function(value) {
	        reactable_bar_style(width = value / max(contigs$contig_length), fill = "#DDDDFF", color = "#000000")
	      },
	      format = colFormat(digits = 0,separators = TRUE,suffix = " bp"),
	      minWidth = 60
	    ),
			GC = reactable_percent_colDef(),
			topology = colDef(
				filterInput = reactable_select_filter('contigs-select'),
				minWidth=50
			),
			is_plasmid = colDef(
				filterInput = reactable_select_filter('contigs-select'),
				minWidth=40
			)
		),
		rowStyle = JS("function(rowInfo) {
	    if (rowInfo.level > 1) {
	      return { background: '#eee', borderLeft: '2px solid #ffa62d' }
	    } else if (rowInfo.level > 0) {
	    	return { background: '#fff', borderLeft: '2px solid #ffa62d' }
	    } else {
	      return { borderLeft: '2px solid transparent' }
	    }
	  }"),
		elementId = "contigs-select",
		class = "feature-tbl contigs-tbl"
	)
```




# Draft

Column
-------------------------



### Resfinder
```{r fig.height=6, fig.width=4}
summarise_resistances(db) |>
	distinct(assembly_id,resistance_name) |>
	mutate(resistance_name = fct_reorder2_hclust(resistance_name,assembly_id,rep(1,n()))) |>
	ggplot(aes(y=resistance_name)) +
	geom_bar() +
	geom_text(aes(x=max(after_stat(count)),label=resistance_name),stat="count",angle=90,hjust=0,size=3) +
	coord_radial("y",rotate.angle = TRUE) + theme_bw() + theme(axis.text = element_blank(),axis.ticks = element_blank(),panel.border = element_blank(),axis.title = element_blank())
```

# Full Map


```{r fig.height=6, fig.width=4, eval=FALSE}
CONTIGS <- contigs |>
	mutate(id = str_c(assembly_id,contig_id)) |>
	filter(is_plasmid) |>
	filter(lengths(resistance_names)>0) |>
	mutate(id=fct_reorder(id,contig_length,mean)) 

p1 <- CONTIGS |>
	ggplot(aes(x=id,y=contig_length)) +
	geom_col()

p2 <- CONTIGS |>
	select(id,resistance_names) |>
	unnest_longer(resistance_names) |> 
	ungroup() |>
	distinct() |>
	mutate(resistance_names=fct_reorder2_hclust(resistance_names,id,rep(1,n()))) |>
	ggplot(aes(x=id,y=resistance_names)) +
	geom_tile() +
	scale_x_discrete(drop=FALSE)

p3 <- CONTIGS |>
	select(id,plasmid_types) |>
	unnest_longer(plasmid_types) |>
	ungroup() |>
	distinct() |>
	mutate(plasmid_types=fct_reorder2_hclust(plasmid_types,id,rep(1,n()))) |>
	ggplot(aes(x=id,y=plasmid_types)) +
	geom_tile() +
	scale_x_discrete(drop=FALSE)


p4 <- CONTIGS |>
	select(id,relaxase_types) |>
	unnest_longer(relaxase_types,keep_empty = TRUE) |>
	ungroup() |>
	distinct() |>
	filter(relaxase_types!="-") |>
	mutate(relaxase_types=fct_reorder2_hclust(relaxase_types,id,rep(1,n()))) |>
	ggplot(aes(x=id,y=relaxase_types)) +
	geom_tile() +
	scale_x_discrete(drop=FALSE)

p1/p2/p3/p4 + plot_layout(axes = "collect_x",heights=c(1,3,3,1))
```




# Assemblies

Row
-------------------------

### Assemblies
```{r}
assemblies |>
	select(mlst_type,assembly_id,num_contig,assembly_length,N50,GC,species_name,orgfinder.species_name,orgfinder.ani) |>
	mutate(GC=100*GC) |>
	group_by(species_name) |>
	gt::gt(row_group_as_column=TRUE) |>
	gt::tab_stubhead("Species Name")  |>
	gt::tab_style(list(gt::cell_text(weight="bold"),gt::cell_fill()),locations=gt::cells_column_labels()) |>
	gt::tab_style(list(gt::cell_text(weight="bold"),gt::cell_fill()),locations=gt::cells_stubhead()) |>		
	gt::fmt_number(c(assembly_length,N50),decimals = 0,pattern="{x} bp") |>
	gt::fmt_number(c(orgfinder.ani,GC),decimals = 1,pattern="{x}%") |>
	gt::tab_style(list(gt::cell_fill(color = "tomato")),locations=gt::cells_body(orgfinder.ani,rows = orgfinder.ani<=97)) |>
	gt::tab_style(list(gt::cell_fill(color = "tomato")),locations=gt::cells_body(orgfinder.species_name,rows = orgfinder.species_name!=species_name))
```


Row
-------------------------

### Assembly Lengths

```{r}
plotly::plot_ly(
	data = assemblies,
	x = ~num_contig,
	y = ~assembly_length,
	text = ~str_glue('
		{assembly_id}
		{sprintf("%s (%.1f%%)",orgfinder.species_name,orgfinder.ani)}
		ST: {mlst_type}
		GC: {sprintf("%.1f%%",100*GC)}
	')
) %>%
plotly::config(displayModeBar=FALSE)
```


### Assembly Lengths
```{r}
contigs |>
	left_join(select(assemblies,assembly_id,species_name,genus_name),by="assembly_id") |>
  mutate(assembly_id = fct_reorder(assembly_id,contig_length,sum)) |>
  mutate(contig_id = fct_reorder(contig_id,contig_length,sum)) |>
  ggplot() + 
      facet_grid(genus_name~.,space = "free_y",scales="free_y") +
      geom_col(aes(x=contig_length,y=assembly_id,group=contig_id,fill=is_plasmid),color="black",position="stack") + 
      scale_x_continuous(position="top",labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
      theme_bw() + theme(legend.position="top") +
			theme(strip.text.y = element_text(angle=0))
```




```{r}
htmltools::tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```

```{css}
.chart-shim {
  overflow: auto;
}


.feature-tbl {
  font-size: 1rem;
  line-height: 1.125rem;
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.contigs-tbl {
}

.assemblies-tbl {
}
```
